server:
  port: ${PORT:0}

kafka:
  groupId: ${GROUP_ID:account-management-${GROUP_ID_POSTFIX:1}}

spring:
  application:
    name: account-management-ws
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: ${DATASOURCE_USER}
      password: ${DATASOURCE_PASSWORD}
      database: ${DATASOURCE_DB_NAME}
      host: ${DATASOURCE_HOST}
      port: ${DATASOURCE_PORT}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoint:
    shutdown:
      enabled: true