spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${DATASOURCE_USER:admin}
      password: ${DATASOURCE_PASSWORD:aaa}
      database: ${DATASOURCE_DB_NAME:accountManagement}
      host: ${DATASOURCE_HOST:localhost}
      port: ${DATASOURCE_PORT:27017}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8082}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.mastore]": DEBUG
    "[org.hibernate]": DEBUG